### ISSUE TITLE
Incompatible with SDK Tools 25, command "list avds" does not exist

### ISSUE THREAD

**Issue by cbergau** [selendroid/selendroid#1107]
Hello,

I don't know about previous versions, but in Version 25, to list all available avds, you need to use "android list avd" instead of "android list avds". 

When i type in

    java -jar selendroid.jar

I get the following output

	Mõr 31, 2017 1:45:31 PM io.selendroid.standalone.SelendroidLauncher main
	INFORMATION: ################# Selendroid #################
	Mõr 31, 2017 1:45:31 PM io.selendroid.standalone.SelendroidLauncher main
	INFORMATION: ################# Configuration in use #################
	Mõr 31, 2017 1:45:31 PM io.selendroid.standalone.SelendroidLauncher main
	INFORMATION: io.selendroid.standalone.SelendroidConfiguration@3b07d329[
	  port=4444
	  timeoutEmulatorStart=300000
	  supportedApps=[]
	  verbose=false
	  emulatorPort=5560
	  deviceScreenshot=false
	  selendroidServerPort=8080
	  keystore=<null>
	  keystorePassword=<null>
	  keystoreAlias=<null>
	  emulatorOptions=<null>
	  keepEmulator=false
	  registrationUrl=<null>
	  proxy=<null>
	  serverHost=<null>
	  keepAdbAlive=false
	  maxSession=5
	  maxInstances=5
	  registerCycle=0
	  noWebViewApp=false
	  noClearData=false
	  sessionTimeoutSeconds=1800
	  forceReinstall=false
	  logLevel=ERROR
	  deviceLog=true
	  serverStartTimeout=20000
	  printHelp=false
	  serverStartRetries=5
	  folder=<null>
	  deleteTmpFiles=true
	]
	Mõr 31, 2017 1:45:31 PM io.selendroid.standalone.SelendroidLauncher launchServer
	INFORMATION: Starting Selendroid standalone on port 4444
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\android
	-driver377826651231336737.apk META-INF/MANIFEST.MF
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Shell command output
	-->

	<--
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\android
	-driver377826651231336737.apk META-INF/CERT.RSA
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Shell command output
	-->

	<--
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\android
	-driver377826651231336737.apk META-INF/CERT.SF
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Shell command output
	-->

	<--
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\android
	-driver377826651231336737.apk META-INF/ANDROIDD.SF
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	SCHWERWIEGEND: Error executing command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\andro
	id-driver377826651231336737.apk META-INF/ANDROIDD.SF
	org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
			at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
			at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
			at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:145)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
			at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
			at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\android
	-driver377826651231336737.apk META-INF/ANDROIDD.RSA
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	SCHWERWIEGEND: Error executing command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\andro
	id-driver377826651231336737.apk META-INF/ANDROIDD.RSA
	org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
			at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
			at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
			at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:146)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
			at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
			at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\android
	-driver377826651231336737.apk META-INF/NDKEYSTO.SF
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	SCHWERWIEGEND: Error executing command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\andro
	id-driver377826651231336737.apk META-INF/NDKEYSTO.SF
	org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
			at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
			at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
			at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:147)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
			at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
			at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\android
	-driver377826651231336737.apk META-INF/NDKEYSTO.RSA
	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	SCHWERWIEGEND: Error executing command: C:\Users\bergau\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe remove C:\Users\bergau\AppData\Local\Temp\andro
	id-driver377826651231336737.apk META-INF/NDKEYSTO.RSA
	org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
			at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
			at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
			at io.selendroid.standalone.android.impl.DefaultAndroidApp.deleteFileFromWithinApk(DefaultAndroidApp.java:112)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.deleteFileFromAppSilently(SelendroidServerBuilder.java:133)
			at io.selendroid.standalone.builder.SelendroidServerBuilder.resignApp(SelendroidServerBuilder.java:148)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initApplicationsUnderTest(SelendroidStandaloneDriver.java:172)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:94)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
			at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
			at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

	Mõr 31, 2017 1:45:32 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Program Files\Java\jdk1.8.0_111\bin\jarsigner.exe -sigalg MD5withRSA -digestalg SHA1 -signedjar C:\Users\bergau\AppD
	ata\Local\Temp\resigned-android-driver377826651231336737.apk -storepass android -keystore C:\Users\bergau\.android\debug.keystore C:\Users\bergau\AppData\Loc
	al\Temp\android-driver377826651231336737.apk androiddebugkey
	Mõr 31, 2017 1:45:33 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Shell command output
	-->
	jar signed.

	Warning:
	No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate
	's expiration date (2047-03-23) or after any future revocation date.
	<--
	Mõr 31, 2017 1:45:33 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
	INFORMATION: App signing output: jar signed.

	Warning:
	No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate
	's expiration date (2047-03-23) or after any future revocation date.
	Mõr 31, 2017 1:45:33 PM io.selendroid.standalone.builder.SelendroidServerBuilder signTestServer
	INFORMATION: The app has been signed: C:\Users\bergau\AppData\Local\Temp\resigned-android-driver377826651231336737.apk
	Mõr 31, 2017 1:45:35 PM io.selendroid.standalone.io.ShellCommand exec
	INFORMATION: Executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\tools\android.bat list avds
	Mõr 31, 2017 1:45:36 PM io.selendroid.standalone.io.ShellCommand exec
	SCHWERWIEGEND: Error executing command: C:\Users\bergau\AppData\Local\Android\sdk\tools\android.bat list avds
	org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
			at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
			at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
			at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:49)
			at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:152)
			at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:124)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
			at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
			at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)

	Mõr 31, 2017 1:45:36 PM io.selendroid.standalone.SelendroidLauncher launchServer
	SCHWERWIEGEND: Error building server: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Users\bergau\AppData\Local
	\Android\sdk\tools\android.bat list avds
	Exception in thread "main" java.lang.RuntimeException: io.selendroid.standalone.exceptions.AndroidDeviceException: io.selendroid.standalone.exceptions.ShellC
	ommandException: Error executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\tools\android.bat list avds
			at com.google.common.base.Throwables.propagate(Throwables.java:160)
			at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:75)
			at io.selendroid.standalone.SelendroidLauncher.main(SelendroidLauncher.java:117)
	Caused by: io.selendroid.standalone.exceptions.AndroidDeviceException: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell comma
	nd: C:\Users\bergau\AppData\Local\Android\sdk\tools\android.bat list avds
			at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:154)
			at io.selendroid.standalone.server.model.DeviceStore.initAndroidDevices(DeviceStore.java:124)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.initAndroidDevices(SelendroidStandaloneDriver.java:185)
			at io.selendroid.standalone.server.model.SelendroidStandaloneDriver.<init>(SelendroidStandaloneDriver.java:95)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.initializeSelendroidServer(SelendroidStandaloneServer.java:63)
			at io.selendroid.standalone.server.SelendroidStandaloneServer.<init>(SelendroidStandaloneServer.java:52)
			at io.selendroid.standalone.SelendroidLauncher.launchServer(SelendroidLauncher.java:65)
			... 1 more
	Caused by: io.selendroid.standalone.exceptions.ShellCommandException: Error executing shell command: C:\Users\bergau\AppData\Local\Android\sdk\tools\android.
	bat list avds
			at io.selendroid.standalone.io.ShellCommand.exec(ShellCommand.java:56)
			at io.selendroid.standalone.android.impl.DefaultAndroidEmulator.listAvailableAvds(DefaultAndroidEmulator.java:152)
			... 7 more
	Caused by: io.selendroid.standalone.exceptions.ShellCommandException: **************************************************************************
	The "android" command is deprecated.
	For manual SDK, AVD, and project management, please use Android Studio.
	For command-line tools, use tools\bin\sdkmanager.bat
	and tools\bin\avdmanager.bat
	**************************************************************************

	Invalid or unsupported command "list avds"

	Supported commands are:
	android list target
	android list avd
	android list device
	android create avd
	android move avd
	android delete avd
	android list sdk
	android update sdk

			... 9 more

**Comment by vls29** [comment]
Having faffed about for two hours trying to get the project to build in Eclipse with maven... I've given up.  But if you check out the code and edit line 148 to read "avd" instead of "avds" here selendroid/selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java Eclipse will compile the code into the target and you can then add it to the jar replacing the old file.

I can't say I've got much further with running the command, but I think that's because in my case I'm trying to link to an existing grid but it's still trying to create one.

**Comment by Neox2891** [comment]
I have the same problem, any solution?

**Comment by ScriptQA** [comment]
I'm also facing the same issue, Can anyone provide any concrete solution to this ?

**Comment by amidbach** [comment]
As per **vls29**'s comments:

- I've donwloaded the sources from https://github.com/selendroid/selendroid/
- edited selendroid/selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/DefaultAndroidEmulator.java
- built again the project using command: ./selendroid-master/selendroid-standalone> gradle build -x test
- and finally got a new selendroid-standalone.jar

**Comment by pedrosmv** [comment]
After I ran the command `gradle build -x test` I got two scripts but I don't know how to make the new  selendroid-standalone.jar. How do I do this? I'm having the same problem

**Comment by luiscruz** [comment]
Same here using the release available in the website..
Is Selendroid dying?..

**Comment by musabu** [comment]
I downloaded selendroid from the source https://github.com/selendroid/selendroid/. Imported it as a project on Android Studio (File|New|Import Project|Locate C:\xxxx\\selendroid-server). It asked me to use graddle 2.2, which I downloaded and provided the path to its location under File|Settings|Build,..|gradle home. And I rebuilt and ran the selendroid server from the studio rather than the command line.

**Comment by rgoerner** [comment]
When compiling, I have this issue, and I am out of my mind, how to fix this :(

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':selendroid-server'.
> Could not resolve all dependencies for configuration ':selendroid-server:_debugCompile'.
   > Could not find com.android.support.test:runner:0.5.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/test/runner/0.5.0/runner-0.5.0.pom
         https://jcenter.bintray.com/com/android/support/test/runner/0.5.0/runner-0.5.0.jar
     Required by:
         selendroid:selendroid-server:0.18.1

**Comment by alexcomsa** [comment]
@rgoerner Did you add the bintrayUser and the bintrayPassword ?

**Comment by rgoerner** [comment]
I got it working with maven ... What a f******* day :)

**Comment by rgoerner** [comment]
https://ufile.io/ku8bl
Here you can find patched version (without any guarantee)

**Comment by gajatko** [comment]
I've reuploaded for grandchildren:
https://ufile.io/cl84i

**Comment by srianant** [comment]
@rgoerner, do you mind sharing the working jar file ? (or) someone else can ?

**Comment by mvall** [comment]
@gajatko @rgoerner, can you reupload the jar file for me?

**Comment by lpetre** [comment]
Fixed in #1134

**Comment by sevetseh28** [comment]
Please can someone build and upload a recent jar file in a decent hosting site that does not expire? It is so complicated to build this. I've endlessly ran into one problem after another...

Thank you

**Comment by philippK-de** [comment]
i have the same problem using "Latest snapshot" version from maven

**Comment by Shrewd** [comment]
So, problem is still not solved on current release, any plans to do so?

**Comment by sixk82** [comment]
I am also having this issue...
Please help in solving it.

**Comment by keithvassallomt** [comment]
For anyone struggling to find a fixed JAR file or compile their own, I've uploaded it here. 
[https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing](https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing)

**Comment by Kerka** [comment]
> For anyone struggling to find a fixed JAR file or compile their own, I've uploaded it here.
> https://drive.google.com/file/d/1YtCr9rV4K73q6c13V6bGSSCPfoRQeUCa/view?usp=sharing

Thank you, but for me it gave exactly the same error like in the first post.
